### ISSUE TITLE
Feature Request: Multi-sig transactions

### ISSUE THREAD

**Issue by destenson** [peercoin/peercoin#119]
I would like to propose that Peercoin add the concept of multi-signature transactions (in addition to multisig wallets). A multi-signature transaction would be a transaction that requires the valid signature of all parties involved before it is actually committed to the blockchain as a valid transaction. A requester or recipient could be any valid address, not just multi-signature wallets. The transaction can be initiated by either the payer or the payee.

Requests for payment can be initiated by party A with a valid signature (or all required signatures if initiated by a multisig wallet) & when party B also signs the request, the actual transfer of funds from B to A will occur like a normal transaction. This will add invoicing as an intrinsic feature to Peercoin.

Outgoing payments to a third-party can also be multisig. In that case, the request is for acceptance of payment, and the transfer is completed when the recipient signs the transaction. Since the transfer is not valid until all parties sign, this allows the funds for the transaction not to be committed until the recipient accepts the payment. If funds are not available when the transaction is adequately signed, it will be rejected by the blockchain due to insufficient funds. A signatory can also rescind their signature before the transaction is accepted by all parties. This allows a fund transfer to be cancelled before payment is accepted. This is a feature that is missing from all major cryptocurrencies.

**Comment by peerchemist** [comment]
just for the record, Peercoin does support multisig transactions for years now.

**Comment by destenson** [comment]
So you're telling me, I can initiate a transaction with peercoin, then have that transaction be approved by the blockchain only when the recipient also approves it?

**Comment by destenson** [comment]
Does peercoin support the type of multi-sig transaction that I'm referring to? Please see [this Monero issue](https://github.com/monero-project/monero/issues/881#issuecomment-351917989) for a much clearer explanation of the concept.
