### ISSUE TITLE
Peercoin doesn't support mining auxpow coins.

### ISSUE THREAD

**Issue by Infernoman** [peercoin/peercoin#129]
Looking for a peercoin pro that may be able to help modify the block serialization code in UNOMP/node-merged-pool so that peercoin can submit blocks successfully to an auxpow network. Currently with the non-optimal headers. It is unable to do so.
https://github.com/UNOMP/node-merged-pool/issues/6
https://github.com/Peerunity/Peerunity/issues/198
https://github.com/Crowndev/crowncoin/issues/28

**Comment by hrobeers** [comment]
Peercoin does not support merged mining.
There have been discussions to implement is, but the community agreed that merged mining is not aligned with peercoin's philosophy.

**Comment by Infernoman** [comment]
I'm not looking to implement merged mining in peercoin but find someone who is able to modify the block header for a pool to submit blocks successfully to an auxpow network. Peercoins block header is different than POW coins so the blocks that get submitted to an auxpow network while mining peercoin do not get accepted.

**Comment by hrobeers** [comment]
AFAIK the block header is the same as for bitcoin:
https://bitcoin.org/en/developer-reference#block-headers
https://wiki.peercointalk.org/index.php?title=Blocks

**Comment by Infernoman** [comment]
The block header is different than bitcoin. It includes a timestamp as well as a signature. This means these fields also get added to the block that the auxpow coin is trying to submit causing it to fail. Part of the block header needs to be stripped down for Peercoin to successfully submit blocks to an auxpow network like Namecoin or IXcoin. This can be done with the pool software that i was linking towards with a bounty. And that's why I need a Peercoin pro.

**Comment by hrobeers** [comment]
I'm a peercoin pro, the block header contains a timestamp just like bitcoin does and it does not contain a signature. proof: https://github.com/peercoin/peercoin/blob/master/src/main.h#L881

I guess you are talking about the coinbase transaction which is indeed different but you don't need it for computing the hash. proof:  https://github.com/peercoin/peercoin/blob/master/src/main.h#L951

Sorry I'm not a merged mining expert, but the block header is exactly the same as bitcoin's.

**Comment by Infernoman** [comment]
I could be incorrect in saying that it is the block header. I'm not as familiar with the issue as some people. And by no means a merged mining expert either, but am working on that. If you take a look at the issue on node-merged-pool. It's explained a bit better. The block that peercoin tries to submit to the AUX network. the auxcoin is not able to decode. and that's why I made the assumption it had to do with the block header. That and that's what I've been told by others as well. https://github.com/UNOMP/node-merged-pool/issues/6

**Comment by hrobeers** [comment]
So I guess you should just fix the calculation of the merkle root. Should be piece of cake for the developer of that mining software.
I have no interest in diving into your code, especially not for such a low reward, but I hope I gave you some insights into what might be causing your issue.
