### ISSUE TITLE
[ppcoin v0.6] Version numbering & node meta-data

### ISSUE THREAD

**Issue by hrobeers** [peercoin/peercoin#136]
The version number is incorrectly displayed in multiple places.
Make sure all node meta-data (version number, ...) is displayed correctly and consistently.

**Comment by belovachap** [comment]
Yeah, I get a version of `v0.4.0ppc-2056-g6e3af8c2-beta` when I compile the daemon on the `v0.6.0ppc.rc1` tag...

I think it uses the output from `git describe` ( https://github.com/peercoin/peercoin/blob/v0.6.0ppc.rc1/share/genbuild.sh#L19 )... maybe we didn't use an annotated tag, that could maybe explain it picking up an old version? https://www.kernel.org/pub/software/scm/git/docs/git-describe.html ("By default (without --all or --tags) git describe only shows annotated tags.").

Maybe one piece of the puzzle :world_map:  :)

**Comment by belovachap** [comment]
I pulled down the second release candidate and now it's a pretty good looking version number :+1: 

`Peercoin version v0.6.0ppc.rc2-beta` :tada:

**Comment by hrobeers** [comment]
Yes we used an annotated tag this time.

**Comment by belovachap** [comment]
Sure, we can always open a new issue if we find another spot that has a weird version string :)

**Comment by sandakersmann** [comment]
Version 0.6.0 shows: "v0.4.0ppc-2090-g91c8c8df-beta" when compiled from master on Ubuntu 17.10.

**Comment by sandakersmann** [comment]
@hrobeers Maybe we should re-open this issue?

**Comment by backpacker69** [comment]
you have to checkout tagged version for this to be correct. ie 
git checkout v0.6.0ppc

**Comment by hrobeers** [comment]
You should build from the release branch release-0.6 or from the release tag v0.6.0ppc like backpacker highlights.

**Comment by hrobeers** [comment]
I'll make sure a tag get's pushed to master once the v0.6.1 beta versions get pushed to master.
