### ISSUE TITLE
checking enforcecheckpoints in daemon

### ISSUE THREAD

**Issue by bananenwilly** [peercoin/peercoin#177]
Is there a way to show the current status of "enforcechekpoints" in the daemon?

Can this be included in getinfo?

**Comment by bananenwilly** [comment]
I'm currently testing branch listtxns-fix2.

getinfo includes a "checkpoints" value, which I can't seem to change.

I tried various settings in .ppcoin/ppcoin.conf. 

getinfo output:
    "checkpoints" : true,

tried in ppcoin.conf:
checkpoints=false
checkpoints=0
enforcecheckpoint=false
enforcecheckpoint=0
enforcecheckpoints=false
enforcecheckpoints=0

**Comment by hrobeers** [comment]
Let's reopen this issue.

**Comment by hrobeers** [comment]
#262 makes sure it is called `enforcecheckpoint` everywhere.
So either:
- `enforcecheckpoint=0` in peercoin.conf
- `-enforcecheckpoint=0` on commandline
- `enforcecheckpoint false` on RPC interface

**Comment by bananenwilly** [comment]
"checkpoints" : false,
works with 
enforcecheckpoint=0

Great work!

**Comment by bananenwilly** [comment]
./testnet-cli -testnet getblockchaininfo | grep check
 ./testnet-cli -testnet getwalletinfo | grep check
 ./testnet-cli -testnet getnetworkinfo | grep check
 ./testnet-cli -testnet -getinfo | grep check

all got nothing. where did it go? 

@peerchemist please reopen

**Comment by backpacker69** [comment]
> for 0.8:
> ./testnet-cli -testnet getblockchaininfo | grep check
> ./testnet-cli -testnet getwalletinfo | grep check
> ./testnet-cli -testnet getnetworkinfo | grep check
> ./testnet-cli -testnet -getinfo | grep check
> 
> all got nothing. where did it go?
> 
> @peerchemist please reopen

that information went to getcheckpoint command, see subscribemode.
it will be either  "enforce" or "advisory" depending on your setting.

**Comment by bananenwilly** [comment]
thank's, closed
