### ISSUE TITLE
qt: command line options window still shows "bitcoin-qt"

### ISSUE THREAD

**Issue by bananenwilly** [peercoin/peercoin#178]
![bb5fd9e6a6c9957933b97a961f49bdccbbffb9d5_1_690x280](https://user-images.githubusercontent.com/11148913/31318253-9b5545c6-ac4f-11e7-9e21-3a0546f2541a.png)

v0.6

**Comment by sandakersmann** [comment]
This is now fixed.

Ref: https://github.com/peercoin/peercoin/pull/174

**Comment by sandakersmann** [comment]
This can be closed now.
