### ISSUE TITLE
Synchronizing Progress Bar Color

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin#180]
I just noticed from one of the screenshots that when the blockchain is synchronizing, the progress bar is still blue and not green like it should be.

I also seem to remember the colors being off on the fields of minting tab, so that should be looked into as well.

**Comment by sandakersmann** [comment]
It's only blue on testnet.

**Comment by captainbuckkets** [comment]
Has this been resolved?

**Comment by sandakersmann** [comment]
Maybe fixed in: https://github.com/peercoin/peercoin/issues/212 ?
@backpacker69 Is this solved?
