### ISSUE TITLE
Status Alert Not Refreshed after Unlock for Minting 

### ISSUE THREAD

**Issue by 7h0m45** [peercoin/peercoin#194]
The status notification bar in the Windows Qt client does not refresh after the wallet is unlocked for minting.
![info](https://user-images.githubusercontent.com/4521509/31499027-264f8494-af29-11e7-878d-2a52cf0400dc.jpg)

**Comment by pffff** [comment]
dont have this issue, could it be because you have an empty wallet? I have some testnet coins
what I did notice in the menu it still says "Decrypt Wallet for Minting Only" after I unlocked my wallet, when clicking it it locks it again (obviously).

**Comment by hrobeers** [comment]
@7h0m45 can you confirm this is fixed in v0.6.1?
