### ISSUE TITLE
Loading Bar doesn't fill up in v0.6

### ISSUE THREAD

**Issue by Nagalim** [peercoin/peercoin#212]
When syncing the chain, there used to be a loading bar that would slowly fill from left to right with green.  That bar still exists, but does not load.  It still goes away as it should when the chain is fully synced, but it never fills at all.

This previously opened issue mentions this bar:
https://github.com/peercoin/peercoin/issues/180

**Comment by hrobeers** [comment]
Can you provide more info on the system you tested it on and with which build?
It works perfectly fine on my system (ArchLinux).

**Comment by hrobeers** [comment]
BTW the bar is blue in the reference client (Peerunity had a green bar)
Could it be that your chain was already >99% synced?
And you were just seeing the full loading bar?

**Comment by Nagalim** [comment]
Definitely not.  This was also seen by sklrd, who thought there was a problem syncing because of the lack of graphic.  Both were on windows, v0.6 release.  Mine was the one built on october 24th, I'm not sure if sklrd was that one or a more recent one.

For proof, I deleted my chain and reproduced the issue:
![image](https://user-images.githubusercontent.com/12321025/32374472-3c65525c-c074-11e7-928d-e695b06ac2a7.png)

**Comment by Sentinelrv** [comment]
If the bar is still blue then it should be green. Blue is not part of our color scheme.
