### ISSUE TITLE
Client crashes in Ubuntu after entering walletpassphrase in Debug-Console with high timeout

### ISSUE THREAD

**Issue by Rakete4** [peercoin/peercoin#215]
I entered the following into the debug-console:

walletpassphrase "mypassphrase" 999999999999999 true

After I hit enter, the client crashes.
My system is a Ubuntu 14.04 64bit.

On Windows 7, it does not crash. I am using the official binaries.

**Comment by backpacker69** [comment]
please advise what version you are running, did you build it yourself? if not, what archive did you use to download and which folder you used 32bit or 64bit?

**Comment by pffff** [comment]
try a couple less nines, now it is same as 31709791 years

**Comment by Rakete4** [comment]
I didn't compile myself. I am using the 64bit Linux binaries that are linked from peercoin.org. 

There seem to be more problems with the "walletpassphrase" command. The client crashed also when I entered 'walletpassphrase "mypassphrase" 0 true' twice, without using "walletlock" in between.

I am not even sure if the walletpassphrase-command really unlocks the wallet, because the padlock-icon on bottom right always remains locked unless I use the unlock-option form the menu.

**Comment by pffff** [comment]
tried here it works without crashing, the padlock icon stays closed when you say it should be unlocked for 0 seconds ofc

**Comment by hrobeers** [comment]
This crash was caused by the Linux pthread timeout which is limited to a 32-bit timeout value.
The windows threads seem to accept 64-bit timeout values.

PR #221 fixes this, by limiting the timeout to max int32, which is 1634 years.
