### ISSUE TITLE
Icon on Windows has White Background Instead of Transparent

### ISSUE THREAD

**Issue by Nagalim** [peercoin/peercoin#226]
Windows 10, 64-bit, version 0.6 built on October 29th.  Docker icon has a white background when it should be transparent.

![image](https://user-images.githubusercontent.com/12321025/32412133-96f5cef8-c1c4-11e7-99cd-44e830274324.png)

**Comment by sandakersmann** [comment]
I made a pull request here: https://github.com/peercoin/peercoin/pull/269

**Comment by hrobeers** [comment]
should be fixed by #269
