### ISSUE TITLE
Client version wrong when building directly from master

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#230]
I get this: **v0.6.1-rc1-11-gb4f65180-beta** when building directly from master without any git checkout.

**Comment by hrobeers** [comment]
That version is correct if you ask me.
You are building from master, not from a release tag or branch.

**Comment by sandakersmann** [comment]
v0.6.1-**rc1**-11-gb4f65180-beta

**Comment by hrobeers** [comment]
Yes rc1 was the last tag on master. We can't call it an official release, can we?
