### ISSUE TITLE
Missing Icons for New Transactions

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin#236]
In the past if you went to the transactions tab and there were brand new transactions, it would show a temporary clock icon that would change the more time progressed until it finally turned into a check mark. This would be helpful for example for knowing when Peercoin from a newly minted block would be available. For some reason the clock icons are not showing anymore and I only see the white check marks. Can anyone else verify this?

**Comment by K210** [comment]
It works on mac.

**Comment by Sentinelrv** [comment]
I am using Linux.
