### ISSUE TITLE
Setting "Enforce checkpoints" needs a tooltip

### ISSUE THREAD

**Issue by jondo** [peercoin/peercoin#240]
I am a newbie and I don't know what this setting means. I noticed that all the other settings have got explanation tooltips - please add it. In the meantime, I hope to get my answer [in the forum](https://talk.peercoin.net/t/what-does-the-setting-enforce-checkpoints-mean/6444).

**Comment by sandakersmann** [comment]
I made a pull request here: https://github.com/peercoin/peercoin/pull/258
