### ISSUE TITLE
Windows "peercoind" binaries fail to run

### ISSUE THREAD

**Issue by 7h0m45** [peercoin/peercoin#243]
It appears the current official **peercoind** binaries for windows (from Peercoin_v0.6.1_win.zip) were compiled with missing libraries.  Error messages refer to _libgcc_s_dw2-1.dll_ and _libstdc++-6.dll_

**Comment by backpacker69** [comment]
there's a fix for this, but there's no point of fixing it as 0.6.2 has completely different build process.

`diff --git a/contrib/gitian-descriptors/gitian-win.yml b/contrib/gitian-descriptors/gitian-win.yml
index 731439b..6cd56ca 100644
--- a/contrib/gitian-descriptors/gitian-win.yml
+++ b/contrib/gitian-descriptors/gitian-win.yml
@@ -71,7 +71,7 @@ script: |
     cp -f release/peercoin-qt.exe $BINDIR/

     cd src
-    make -f makefile.linux-mingw $MAKEOPTS HOST=$HOST DEPSDIR=$STAGING peercoind.exe USE_UPNP=0 DEBUGFLAGS="-frandom-seed=nu"
+    make -f makefile.linux-mingw $MAKEOPTS HOST=$HOST DEPSDIR=$STAGING peercoind.exe USE_UPNP=0 DEBUGFLAGS="-frandom-seed=nu" LDFLAGS="-static-libgcc -static-libstdc++"
     ${HOST}-strip peercoind.exe
     cp -f peercoind.exe $BINDIR/
`

**Comment by peerchemist** [comment]
@backpacker69 can we fix it for 0.6.1 branch (master) and issue a point release.

**Comment by hrobeers** [comment]
@peerchemist not master, release-0.6

**Comment by hrobeers** [comment]
@backpacker69 can't we just update the windows binaries without changing the gitian files in the repo?
Just add the missing dlls and upload.

**Comment by backpacker69** [comment]
try Peercoin_v0.6.1_win_static.zip
