### ISSUE TITLE
JSON parse failure

### ISSUE THREAD

**Issue by hrobeers** [peercoin/peercoin#248]
when doing
`walletpassphrase *** 9999999 true`
or
`walletpassphrase *** 9999999 1`

both return the following error, unlock the wallet successfully but ignore the bool at the end.
`value is type str, expected bool (code -1)`

**Comment by hrobeers** [comment]
@backpacker69 it seems PR https://github.com/peercoin/peercoin/pull/232 introduced this bug.

**Comment by bananenwilly** [comment]
```
./peercoind enforcecheckpoint false
error: {"code":-1,"message":"value is type str, expected bool"}
```

```
./peercoind enforcecheckpoint 0
error: {"code":-1,"message":"value is type str, expected bool"}

```

**Comment by hrobeers** [comment]
Still some issues with the RPC are left over from the autotools merge.

**Comment by hrobeers** [comment]
#260 should fix all rpc parsing issues.

**Comment by bananenwilly** [comment]
Working, great fix!
