### ISSUE TITLE
Hardened Checkpoints

### ISSUE THREAD

**Issue by Nagalim** [peercoin/peercoin#253]
The last hardened checkpoint was at a block found on 08/03/2013.

This is a comment in the code (src/checkpoints.cpp):
    // What makes a good checkpoint block?
    // + Is surrounded by blocks with reasonable timestamps
    //   (no blocks before with a timestamp after, none after with
    //    timestamp before)
// + Contains no strange transactions

The only thing I'm unsure of is how far back to take the block from the current end of the chain.

Don't forget to fill out the checkpoint data as well as the block hash and number.

**Comment by sandakersmann** [comment]
I made a pull request here: https://github.com/peercoin/peercoin/pull/254
