### ISSUE TITLE
Blank/Missing Menu Button Text When Running Client with Cyrilic Font

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin#255]
This is a bug that seems to have carried over from Peerunity. It was previously reported from someone using the client in Russian that the text on the menu buttons were missing and appeared blank. You can see an image here...

https://talk.peercoin.net/t/topic/4571

This was just reported in chat and it seems to be the same thing, but in the v0.6 client...

https://i.imgur.com/MqdCYqe.png

Notice the Russian text in the blue title bar at the top of the client.

**Comment by belovachap** [comment]
Oh man... that's not great. I might be able to take a peek at this later... kind of curious what went wrong there 🤔

**Comment by peerchemist** [comment]
It's our selection of font. Font we use does not have Cyrillic symbols. We must find proper font package.

**Comment by sandakersmann** [comment]
I made a pull request here: https://github.com/peercoin/peercoin/pull/268

**Comment by hrobeers** [comment]
is this fixed now that I merged #268 ?

**Comment by sandakersmann** [comment]
I hope so, but I think we should get some confirmation from those who actually have the bug.

**Comment by sandakersmann** [comment]
Maybe compile a windows version for them to try out.

**Comment by sandakersmann** [comment]
Looks like this issue is fixed in 0.6.2

https://talk.peercoin.net/t/topic/4571/30/
