### ISSUE TITLE
OSX Display Issues

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin#259]
First reported here...

https://www.reddit.com/r/peercoin/comments/7gcpp6/peercoin_core_v06_wallet_mac_feedback/

-Not optimised for mac retina display, results in blurry interface
-On transactions page the scrolldown bar is blocking the amount column 
-Spinning wheel on the bottom that shows blockchain is syncing is missing

Screenshots were provided...

https://imgur.com/7Wn8i4I

https://imgur.com/a/ZtmwH

He explains that Peerunity was optimized for Mac retina displays, but v0.6 was not.

Backpacker confirmed that scroll bars do cover some of the text, but he doesn't have a retina display to test this. Anybody have one that can help with testing?

**Comment by K210** [comment]
I am the one who originally posted about this bugs on reddit. 

I have a retina display that can be used for tested if necessary.

**Comment by charliegama** [comment]
Hello have managed to compile the mac version, help me

**Comment by captainbuckkets** [comment]
Will be resolved in rebase with the move to QT5
