### ISSUE TITLE
LibLevelDb error

### ISSUE THREAD

**Issue by FndNur1Labs** [peercoin/peercoin#261]
cd /root/Downloads/peercoin/src/leveldb && CC=gcc CXX=g++ make OPT="-m64 -pipe -fstack-protector-all -D_FORTIFY_SOURCE=2 -O2" libleveldb.a libmemenv.a
make[1]: Entering directory '/root/Downloads/peercoin/src/leveldb'
/bin/sh: 1: ./build_detect_platform: not found
Makefile:18: build_config.mk: No such file or directory
make[1]: *** No rule to make target 'build_config.mk'.  Stop.
make[1]: Leaving directory '/root/Downloads/peercoin/src/leveldb'
Makefile:613: recipe for target '/root/Downloads/peercoin/src/leveldb/libleveldb.a' failed
make: *** [/root/Downloads/peercoin/src/leveldb/libleveldb.a] Error 2

**Comment by belovachap** [comment]
Huh, weird... which branch / tag are you trying to build and on what architecture? Is there a specific set of instructions you were following to compile that we could also follow along with to reproduce?

**Comment by FndNur1Labs** [comment]
i used debian 8. err i compile master.....is there need another
branch...will try then~

**Comment by FndNur1Labs** [comment]
Debian 8 x64bit, yes i follow doc. and i used master that it.

**Comment by hrobeers** [comment]
That issue appeared on some linux distros like debian, due to a confusion between header includes.
The move to autotools should have fixed this issue.

Please try compiling the latest master branch using:
```
./autogen.sh
./configure
make -j
```

**Comment by FndNur1Labs** [comment]
configure: error: Found Berkeley DB other than 4.8, required for portable wallets (--with-incompatible-bdb to ignore or --disable-wallet to disable wallet functionality)

**Comment by hrobeers** [comment]
You need to have berkeley DB v4.8 installed to make sure old wallet.dat files can be loaded.
If you don't care you can use --with-incompatible-bdb but make sure you know what you're doing in that case, otherwise just install berkeley DB 4.8 and all will be fine.

closing this issue as it's not a bug.

**Comment by hrobeers** [comment]
@FndNur1Labs  BTW you seem to be logged in as root not a good idea.
