### ISSUE TITLE
qt: Missing transactions in minting view?

### ISSUE THREAD

**Issue by SeverinDK** [peercoin/peercoin#270]
I upgraded to 0.6 a few days ago and noticed that I am missing a transaction in the minting view. When I was using PeerUnity, I could see two transactions in my wallet. One for 704.391686 and one for 0.98. After upgrading to 0.6 I could only see the 704.391686 transaction, but in the main view, I could still see a total of 705.371686.

**These first two screenshots are a few days old.**
<img width="1093" alt="screen shot 2017-12-09 at 03 37 59" src="https://user-images.githubusercontent.com/1542119/33804238-0d5895ec-dda1-11e7-8dfe-bda15ed51497.png">
<img width="1093" alt="screen shot 2017-12-09 at 03 38 07" src="https://user-images.githubusercontent.com/1542119/33804240-11b5646c-dda1-11e7-9d1e-0d0d43b0b33d.png">

**After generating a block yesterday: (Still missing ~1 PPC)**
<img width="1128" alt="screen shot 2017-12-10 at 11 56 56" src="https://user-images.githubusercontent.com/1542119/33804253-40228f3c-dda1-11e7-9169-f4c57cc887be.png">
<img width="1126" alt="screen shot 2017-12-10 at 11 56 18" src="https://user-images.githubusercontent.com/1542119/33804254-42735802-dda1-11e7-821b-ba97ed57b15a.png">
After hitting the block I have a total of 705.491686 for minting, but a totalt of 706.471686 in the main view. I see the 0.98 as available after generating a block, but still not in the minting view? I dont know if it matters, but the 0.98 transactions is > 150 days old.

**Comment by SeverinDK** [comment]
Not sure how or why, but not the missing transaction is there.

![screen shot 2017-12-12 at 08 25 11](https://user-images.githubusercontent.com/1542119/33872168-05dd311c-df16-11e7-9dd3-f753c64e3b5f.png)

**Comment by lbesaw** [comment]
This has happened to me as well, I had 2 500 ppc transactions from a split and now one is missing, all other transactions in my minting view are present
