### ISSUE TITLE
The soft fork just turned into a hard fork

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#271]
Reported here: https://talk.peercoin.net/t/v0-6-soft-fork-watcher-thread-over-60/6304/6

**Comment by sandakersmann** [comment]
@hrobeers @peerchemist @sunnyking @sigmike Can you guys take a look at this?

**Comment by Nagalim** [comment]
Sunny sent a priority 2500 alert.  He has now replaced it with a priority 900 alert, so everything should work now.

**Comment by peerchemist** [comment]
resolved.

**Comment by hrobeers** [comment]
Was it a hard fork?
It seems the 0.5 clients just got stuck, no fork at all.
