### ISSUE TITLE
Remove PoW mining code from the wallet.

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin#272]
https://www.reddit.com/r/peercoin/comments/7iwi00/are_there_any_plans_to_seperate_the_code_for/?utm_content=title&utm_medium=hot&utm_source=reddit&utm_name=peercoin

Peercoin can't be mined on consumer hardware anyway, so this code is only making us problems by triggering antivirus software on Windows OS.

**Comment by hrobeers** [comment]
Interesting, we'll need to find a solution for testnet nodes, maybe a compile flag?
Any other idea @backpacker69 ?

**Comment by hrobeers** [comment]
The minting code shares a lot with the mining code. So I fear removing the mining code will still trigger virus scanners.

We can create a build that is unable to mine and mint so people with virus scanners are still able to run the default wallet.

**Comment by linalouise9** [comment]
More broadly (maybe separately) might want to also consider SPV wallets.

**Comment by Cybnate** [comment]
This scares of new users. Just had to manage another one new to Peercoin. I believe we should include how to verify the signatures in the instructions. Most people won't have a clue. Just instructing them to assume it is safe and hit 'allow' when their virus-scanner alerts is very bad practice. Helping them to verify the files would support them in doing the right thing.
