### ISSUE TITLE
Peercoin v0.6.1 cannot send transaction

### ISSUE THREAD

**Issue by got3nks** [peercoin/peercoin#277]
Since upgrading to Peercoin v.0.6.1, we cannot send transactions anymore:

`TopUpKeyPool() : writing generated key failed`

`CDB() : can't open database file wallet.dat, error -30974`

**Comment by got3nks** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

Running binary 64bit linux version downloaded from https://peercoin.net/wallet

**Comment by hrobeers** [comment]
@backpacker69 @peerchemist Can you check this package is built against BerkeleyDB 4.8 ?

@got3nks as quick fix you can try to export your keys using `dumpprivkey <address>` command using the old wallet and import them after starting v0.6.1 without a wallet.dat file using `importprivkey <private-key>`

**Comment by got3nks** [comment]
We have a lot of addresses so that's not easy.

**Comment by backpacker69** [comment]
backup your wallet.dat and try running peercoind with -salvagewallet, it should recover all private keys. after that you can rescan, and all balances should be correct.

**Comment by got3nks** [comment]
We have downgraded to the old Peercoin client, hopefully this issue will be fixed in future versions.

**Comment by backpacker69** [comment]
what is the version of peercoin you are using? peerunity or ppcoin?

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by backpacker69** [comment]
@got3nks can you please run ldd on your working peercoin client and also provide md5 of it?

**Comment by got3nks** [comment]
Peercoin_v0.6.1_linux.zip
09e3e26f0b721c797e4df9997fa33159  peercoind

```
~/peercoin$ ldd peercoind.v0.6.1
	linux-vdso.so.1 =>  (0x00007ffd5cfd6000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fd37f2a0000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fd37ef93000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fd37ec8d000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fd37ea76000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fd37e6b1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fd37f4be000)
```

**Comment by backpacker69** [comment]
@got3nks sorry, I meant what ldd on your working version returns, the one you went back to. and md5 of it

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by got3nks** [comment]
9823f387e4609ded45b455bb6734c957  peerunityd

```
~/peercoin$ ldd peerunityd
	linux-vdso.so.1 =>  (0x00007ffeb39cf000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f225368c000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f225337f000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2253079000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2252e62000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2252a9d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f22538aa000)
```
