### ISSUE TITLE
Error on build osx

### ISSUE THREAD

**Issue by SebDigital** [peercoin/peercoin#28]
Hi,

I have this error when I build the project, let me know what I am doing wrong, cheers Seb

opt/local/lib -o build/macdockiconhandler.o src/qt/macdockiconhandler.mm
src/qt/macdockiconhandler.mm:50:39: error: assigning to 'objc_object *' from
      incompatible type 'DockIconClickEventHandler *'
  ...= [[DockIconClickEventHandler alloc] initWithDockIconHandler:this];
     ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/qt/macdockiconhandler.mm:60:6: warning: receiver type 'objc_object *' is not
      'id' or interface pointer, consider casting it to 'id' [-Wreceiver-expr]
    [this->m_dockIconClickEventHandler release];
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by emeth-** [comment]
I had the same error - I made these changes to get past it:
https://github.com/ppcoin/ppcoin/compare/master...Peerapps:osx_build
