### ISSUE TITLE
Cant connect to RPC server

### ISSUE THREAD

**Issue by woblit** [peercoin/peercoin#285]
Just installed the 0.6.1 release on Linux (Ubuntu). I have got other bitcoind based daemons running and can connect to the RPC servers on these, however, for some reason I cannot connect to the RPC server on Peercoin (QT) after config has been setup correctly. 

It will make a connection, bit then as soon as data is sent to the connected socked it disconnects. As mentioned, other Bitcoin based coins seem to work with RPC without a hassle.

**Comment by peerchemist** [comment]
Can you give me your peercoin.conf file please?

**Comment by woblit** [comment]
Sure. This is the file I am using:

rpcuser=MyUser
rpcpassword=MyPass
rpcallowip=127.0.0.1
rpcallowip=22.x.x.144
rpcport=35200
rpctimeout=60
server=1
gen=0
listen=1

**Comment by peerchemist** [comment]
can you run the daemon with the `-daemon` flag and post relevant errors here?

**Comment by woblit** [comment]
When trying to connect to the daemon: 

telnet localhost 35200
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
[Tried to enter some text]
Connection closed by foreign host.

When trying to connect to another daemon based on bitcoin:

telnet localhost 31200
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.

[Tried to enter some text]

HTTP/1.1 400 Bad Request
Content-Type: text/html
Connection: close
Date: Thu, 14 Dec 2017 23:41:31 GMT
Content-Length: 94

<HTML><HEAD>
<TITLE>400 Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
</BODY></HTML>
Connection closed by foreign host.

So there is some response back from the RPC server. Seems like the peercoin RPC server doesn't respond in the same way for some reason. 

Don't know if this helps at all.. :)

**Comment by hrobeers** [comment]
does the peercoind command work?
e.g. `peercoind getinfo` ?

Does removing `rpcallowip=22.x.x.144` make a difference?

In any case it is bad practice to expose your rpc port to the outside world, it is recommended to block the rpc port by your firewall and only connect locally. If for some reason you really need to access it from outside, I recommend using port forwarding over ssh.
