### ISSUE TITLE
Cross compile windows?

### ISSUE THREAD

**Issue by linalouise9** [peercoin/peercoin#300]
Is it possible to cross compile peercoin on linux for windows? If so anyone know the commands?

I tried to follow how bitcoin cross compiles, though didn't make much progress.

Would also like to add the cross compile to the travis builds.

**Comment by peerchemist** [comment]
https://github.com/peercoin/peercoin/wiki/Compiling-for-Windows-on-Debian-linux

**Comment by linalouise9** [comment]
Created pull request #303. If someone knows how to speed up build they can submit another request

**Comment by linalouise9** [comment]
#314 uses mxe packages, speeds up build

**Comment by linalouise9** [comment]
Closing. Packages compile and merged.
