### ISSUE TITLE
Text Kerning

### ISSUE THREAD

**Issue by Nagalim** [peercoin/peercoin#305]
All three menus have this issue.  This is on my friend's laptop, windows 10, so it's hard to give system details.  If you have specific questions I can ask.  My windows computer doesn't have this issue.

![txtissue](https://user-images.githubusercontent.com/12321025/34650651-8fc68686-f392-11e7-976d-7267f01f5a3e.jpg)

**Comment by pffff** [comment]
could it have to do with scaling, windows has some options for Scale and layout under Display settings

**Comment by captainbuckkets** [comment]
Will be resolved in Rebase.  Needs a QT5 feature and we are current on QT4

**Comment by peerchemist** [comment]
Closing because v0.8 is around the corner.
