### ISSUE TITLE
Release tag v0.6.1 reporting "bitcoin" filename/text-message for daemon instead of peercoin?

### ISSUE THREAD

**Issue by typoworx-de** [peercoin/peercoin#308]
Release tag v0.6.1 reporting "bitcoin" filename/text-message for daemon instead of peercoin?

**Comment by typoworx-de** [comment]
The pre-compiled version correctly reports itself as "peercoin" instead of bitcoin.
https://github.com/peercoin/peercoin/releases/download/v0.6.1ppc/Peercoin_v0.6.1_linux.zip

**Comment by hrobeers** [comment]
v0.6.1 is bitcoin v0.6.1 look for v0.6.1ppc instead as shown here: https://github.com/peercoin/peercoin/releases
