### ISSUE TITLE
peercoin-cli has exit codes reversed

### ISSUE THREAD

**Issue by backpacker69** [peercoin/peercoin#313]
peercoin-cli has exit codes reversed, it exits with code 1 when there's no error and code 0 when there's. for example:

$ ./peercoin-cli getaccount
error: {"code":-1,"message":"getaccount <peercoinaddress>\nReturns the account associated with the given address."}
$ echo $?
0

$ ./peercoin-cli getnewaddress
PUGW98DXdGJYpFT5Dbk4DkWQLRvhbWCupK
$ echo $?
1

**Comment by peerchemist** [comment]
this is interesting, can you handle this before we tag 0.6.2?
