### ISSUE TITLE
Boost lib version detection failing on non x86_64 linux platforms

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin#323]
Compilation log is vague:

```
[checking for boostlib >= 1.20.0... yes
checking whether the Boost::System library is available... yes
configure: error: Could not find a version of the library!
```

The problem seems to be similar to following Bitcoin issue: https://github.com/bitcoin/bitcoin/issues/3219

**Comment by hrobeers** [comment]
After reading through that issue, the fix is as follows:

on i386 linux: `./configure --with-boost-libdir=/usr/lib/i386-linux-gnu`
on ARM linux: `./configure --with-boost-libdir=/usr/lib/arm-linux-gnueabihf`

As far as I can see nothing other than adding a note about this to the docs has been done.

**Comment by peerchemist** [comment]
Should this not be handled by the configure script?

**Comment by hrobeers** [comment]
As far as I'm aware, these dependency resolution scripts are centrally maintained and are not meant to be edited by individual projects. But let's see what our autotools expert has to say about this @backpacker69

**Comment by peerchemist** [comment]
This is causing me problems with Debian build system.

**Comment by peerchemist** [comment]
I have just tested the same setup, on same machine with bitcoin-core 0.15.1 and it works fine without explicit statement on boostlib location.

**Comment by peerchemist** [comment]
https://github.com/peercoin/peercoin/pull/325

has fixed the problems for i386 but not for armh. Further testing is required.
