### ISSUE TITLE
failed to build install.sh on Raspberry Pi 

### ISSUE THREAD

**Issue by charleshsu168** [peercoin/peercoin#326]
Excessive CPU usage caused the Raspberry Pi to freeze..
running on RPI 3. 
[](url)
![img_20180128_152930](https://user-images.githubusercontent.com/5799190/35488638-753d0614-0440-11e8-96b7-530585702b09.jpg)
![img_20180128_152925](https://user-images.githubusercontent.com/5799190/35488639-7559673c-0440-11e8-85c3-fd5f8d725db3.jpg)

**Comment by charleshsu168** [comment]
I am curious to know if anyone has any luck successfully compiling the latestest peercoin on raspberry pi 3?

**Comment by hrobeers** [comment]
This is not a peercoin issue, but an RPI issue.
RPI packages are typically cross compiled on a more powerful machine.

You can try compiling using less cores using `make -j2` (for using 2 cores instead of 4)

I'm closing this issue as it's not peercoin related.
