### ISSUE TITLE
Segfault On method=submitblock

### ISSUE THREAD

**Issue by RamJett** [peercoin/peercoin#337]
Segfault instantly on solo mining test. As soon as a block is submitted, segfault. 
"v0.6.1ppc  Ubuntu-16.04 on testnet but also tried on master with same results."

debug.log:
<pre>...
2018-02-08 20:14:28 ThreadRPCServer method=getblockcount
2018-02-08 20:14:28 ThreadRPCServer method=getblockhash
2018-02-08 20:14:28 ThreadRPCServer method=submitblock</pre>

At this point a segfault and peercoind is dead.
gdb output:
<pre>Thread 20 "peercoind" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb67fc700 (LWP 26112)]
0x000000000054c554 in CScript::IsPayToScriptHash (this=this@entry=0x8) at script.cpp:1839
1839    script.cpp: Permission denied. </pre>

dmesg output:
<pre>...
segfault at 8 ip 000000000054c554 sp 00007f26bdff9f20 error 4 in peercoind[400000+2c9000]</pre>

ppcoin.conf:
<pre>server=1
daemon=1
listen=1
maxconnections=10
rpcuser=myuser
rpcpassword=mypass
rpcport=19902
rpcallowip=127.0.0.1
rpcallowip=192.168.50.*
bind=127.0.0.1:19388
port=19388
testnet=1</pre>

**Comment by RamJett** [comment]
Is there a easy way you suggest I capture this? My method I'm using is a modified cgminer for ppc direct to the rpc . No stratum between.

**Comment by hrobeers** [comment]
Are you using the getwork rpc method?
This one has been abandoned for years as it is not capable of mining >4GH/s

You need a stratum server that uses getblocktemplate to mine these days.

**Comment by RamJett** [comment]
I'm guessing if you say it is 'abandoned', it should not give miner the option and segfault on submission, so still would consider this a bug if this is true. This method of mining works fine on my test net for BTC and BCH.Using a mandatory stratum kinda defeats the lottery solo mining method.
