### ISSUE TITLE
Clang compile - leveldb error

### ISSUE THREAD

**Issue by linalouise9** [peercoin/peercoin#341]
Unable to compile peercoin using clang, receiving leveldb error. Is leveldb being built differently from the rest of the peercoin codebase?

../src/leveldb/libmemenv.a: error adding symbols: Archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by bibz0r** [comment]
I also encounter this problem, but only when trying to cross-compile from Ubuntu 16.04 for Windows..

> /home/bibz/newpeer/peercoin/src/leveldb/libmemenv.a: error adding symbols: Archive has no index; run ranlib to add one

**Comment by backpacker69** [comment]
please specify your build commands and whether it's still a problem

**Comment by peerchemist** [comment]
Closing because v0.8 is around the corner.
