### ISSUE TITLE
Unable to run peercoind after build, boost assertion

### ISSUE THREAD

**Issue by bibz0r** [peercoin/peercoin#357]
After successfully (?) creating my genesis block I'm trying to run peercoind, but I get this error:

> bibz@bibz-u:~/peercoin/src$ ./peercoind 
> peercoind: /usr/local/include/boost/thread/pthread/condition_variable_fwd.hpp:114: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
> Aborted (core dumped)

As the README states I installed the libboost-all-dev package:

> bibz@bibz-u:~/peercoin/src$ dpkg -l | grep boost
> ii  libboost-all-dev                            1.58.0.1ubuntu1                              amd64        Boost C++ Libraries development files (ALL) (default version)
> 

My system:

> bibz@bibz-u:~/peercoin/src$ uname -a
> Linux bibz-u 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
> bibz@bibz-u:~/peercoin/src$ cat /etc/issue
> Ubuntu 16.04.4 LTS \n \l

I also tried removing libboost-all-dev and compiling the newest version of boost, but that did not help. 

Is this issue even related to boost or did I fail at the genesis creation?

**Comment by backpacker69** [comment]
we don't provide free support to peercoin forks.

**Comment by bibz0r** [comment]
Where did I state that this is a fork? I'm just playing around with the coin.

Also what does it mean "free support"? This is github not a forum, right?
