### ISSUE TITLE
Change addresses not showing in qt and peercoind

### ISSUE THREAD

**Issue by cornac** [peercoin/peercoin#370]
peercoind not showing change addresses. But balance completely showing with changes by getbalance method. Private key of change addresses can be dumped. Import key to the same wallet ending with error: {"code":-4,"message":"Error adding key to wallet"}

**Comment by backpacker69** [comment]
where do you expect them to be seen?

-------- Original Message --------

**Comment by cornac** [comment]
expect to see it on getaddressesbyaccount method answere and into in addresses list in "Recive" tab in peercoin-qt

**Comment by cornac** [comment]
Close issue, pls. Address showing without user intervention after passing several hours
