### ISSUE TITLE
Non deterministic signature

### ISSUE THREAD

**Issue by Vasiliy-Bondarenko** [peercoin/peercoin#386]
I don't understand - why signature is not deterministic?
I'm signing the same raw transaction hex with a node and always get different result.
Where this difference is coming from? It is not timestamp in transaction - i'm signing same hex every time.

**Comment by backpacker69** [comment]
> I don't understand - why signature is not deterministic?

elliptic curve signatures are non deterministic by [design](https://en.wikipedia.org/wiki/Elliptic_Curve_Digital_Signature_Algorithm), each signature is unique.
