### ISSUE TITLE
Link to website in about dialog

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin#392]
https://talk.peercoin.net/t/peercoin-release-0-6-4/8520/4

The "About Peercoin" dialog should have a link to https://peercoin.net/.

**Comment by captainbuckkets** [comment]
Will look into this.

**Comment by captainbuckkets** [comment]
https://github.com/peercoin/peercoin/pull/422/commits/ac76ca532a8869e2b9a4bcf77c231de3fda34393

**Comment by captainbuckkets** [comment]
![image](https://user-images.githubusercontent.com/24922789/52839108-8c746780-30ba-11e9-9d8a-0169dc5de5e2.png)

Please close.
