### ISSUE TITLE
Rebase scaling

### ISSUE THREAD

**Issue by captainbuckkets** [peercoin/peercoin#443]
Increasing scaling > 100% creates graphical errors.  This issue cannot be fixed in QT4.  These settings will need to be added in a config file somewhere https://doc.qt.io/qt-5/highdpi.html#microsoft-windows

Example: 
https://cdn.discordapp.com/attachments/470532497587830787/542500835649650699/unknown.png

**Comment by peerchemist** [comment]
Closing because v0.8 is around the corner.
