### ISSUE TITLE
When building ./configure ignores flags

### ISSUE THREAD

**Issue by cryptopool-builders** [peercoin/peercoin#456]
Hello I am trying to build peercoin but when I use the following 

`./configure CPPFLAGS="-I${STORAGE_ROOT}/berkeley/db4/include -O2" LDFLAGS="-L${STORAGE_ROOT}/berkeley/db4/lib" --without-gui --disable-tests`

it is ignoring the locations for berkeley and errors out with 

`configure: error: libdb_cxx missing, Bitcoin Core requires this library for wallet functionality (--disable-wallet to disable wallet functionality)`

And yes ${STORAGE_ROOT} is set, and yes this is the only coin so far doing this. All other coins build fine. And it is version 4.8 in that file location.

**Comment by backpacker69** [comment]
if you are building from release-0.7 branch, which is based on older bitcoin, it expects berkeley db to be in few specific locations in relation to root of build directory (namely db4, bdb4, libdb4 amongst them). there is a helper script to help you install it so configure process finds them. 

`bash ./contrib/install_db4.sh ./`

**Comment by cryptopool-builders** [comment]
Im building from the 7.1 master branch. the helper script basically does what i already have done for my install locations.

**Comment by peerchemist** [comment]
Please mind that berkeley v4 is not a strict requirement, v5 can be used if you have no need to support older clients.
