### ISSUE TITLE
Missing Balances

### ISSUE THREAD

**Issue by captainbuckkets** [peercoin/peercoin#459]
Have had this issue since v0.7 went live.  A reinstallation did not fix the issue.  I have tried repairwallet and salvagewallet.  Its almost pointless to use as I cannot see how or where anything is.  

![image](https://user-images.githubusercontent.com/24922789/54696705-4e73c480-4afa-11e9-84d6-0e4a2ac8e9f4.png)

![image](https://user-images.githubusercontent.com/24922789/54696749-64818500-4afa-11e9-97ed-b0b5d0b8c520.png)

You can see where the amounts are non-existent as well.  I can live with this until I find a solution, but it still makes little to no sense why it happened and there is no clear fix.

**Comment by backpacker69** [comment]
does opening your wallet.dat in 0.6 reveal any balances

**Comment by backpacker69** [comment]
change units to mppc and then back to ppc

**Comment by captainbuckkets** [comment]
> change units to mppc and then back to ppc

This fixed it.  Who would have thought...
