### ISSUE TITLE
qt theme issues in release-0.8

### ISSUE THREAD

**Issue by backpacker69** [peercoin/peercoin#460]
@captainbuckkets

* combobox colours are off in Send and Receive tab and in multisig dialog 'spend funds'.
* debug window header and body unreadable
* transaction details unreadable
* coincontrol dialog is unreadable

**Comment by backpacker69** [comment]
updated issue with more visual bugs

**Comment by captainbuckkets** [comment]
Can you explain what you mean by transaction detail?  Want to make sure we are on the same page.  Working on the send tab atm
