### ISSUE TITLE
App crash on multisig tab

### ISSUE THREAD

**Issue by Vitalicus** [peercoin/peercoin#471]
In windows 10, on multisig tab when I click "paste public key" or "choose address" it crash the application.
peercoin-0.8.0-win64-setup-unsigned.exe

**Comment by sunnyqueen** [comment]
same here, it works a little bit when first copying an address, it doesn't crash when click "paste public key" and afterwards click "choose address", but it still crashes when first clicked on "choose address" even with public key in clipboard memory

**Comment by peerchemist** [comment]
Closing because v0.8 is around the corner. Multisig tab is removed in the v0.8.
