### ISSUE TITLE
Large amount of futex syscalls (100% usage) when minting

### ISSUE THREAD

**Issue by Demindiro** [peercoin/peercoin#477]
### Description

When unlocking my wallet for minting, I noticed that one of the threads uses 100% of the CPU. Using `strace -f -p 30064` I get the following output:
```
[pid 30099] futex(0x74d16f08, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 30099] futex(0x74d16f08, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 30099] futex(0x74d16f08, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 30099] futex(0x74d16f08, FUTEX_WAKE_PRIVATE, 1) = 0
[pid 30099] futex(0x74d16f08, FUTEX_WAKE_PRIVATE, 1) = 0
...
```
times a billion.

I've tried to use GDB to figure out what thread is doing:

- Frequently in `__udivmoddi4`
- Also quite often `__pthread_mutex_unlock_usercnt`
- Sometimes `__offtime`

Also some other functions but really not often.

I'll try to install a version with debug symbols to figure out what is going on.

---

### System details
| | |
| --- | --- |
Distributor ID | Raspbian
Description | Raspbian GNU/Linux 9.8 (stretch)
Release | 9.8
Codename | stretch
`uname -a` | Linux tunnel 4.14.79-v7+ #&zwj;1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

**Comment by backpacker69** [comment]
what package are you using

**Comment by Demindiro** [comment]
`raspbian-peercoind_0.7.3-1_armhf.deb`

**Comment by backpacker69** [comment]
can you please try 0.8 rc9

**Comment by Demindiro** [comment]
It doesn't seem to be an issue in 0.8.
