### ISSUE TITLE
minting updateWallet randomly makes application unresponsive

### ISSUE THREAD

**Issue by bananenwilly** [peercoin/peercoin#495]
**Problem**:
I've recently experienced serious performance issues with peercoind on my testnet faucet. 

Reading the debug.log, I found thousands of entries like this:

```
2019-11-17 10:32:23 minting updateWallet 2449c930b86a6f82e582d4b9e429e5677c1519a1fb3f52184833254c49dc6119 0
2019-11-17 10:32:23    inWallet=1 inModel=0 Index=342-342 showTransaction=1 derivedStatus=0
```

While this cycle is running, the application will not respond to ^C or SIGHUP for minutes, sometimes not at all.

**Behavior**: System eventually runs out of memory. 

**Troubleshooting**:
I tried salvaging the wallet and re-syncing from scratch. It did not help. 

**Application**: peercoind, peercoin-qt 0.8.4

**Debug.log**: 
https://peercoinexplorer.net/debug/debug.log (~100 mb)

**Comment by backpacker69** [comment]
try nominting option

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by bananenwilly** [comment]
I can try that, but I think I've been explicitly asked to mint with that testnet wallet, since it's mighty rich.

**Comment by bananenwilly** [comment]
I'm starting the testnet node with the following command:

ExecStart=/home/node/testnetd -nominting -testnet

(I also tried it the other way around with -testnet -nominting) 

and yet I still see
2019-11-19 20:46:13 CPUMiner started for proof-of-stake

in debug.log 

and I also see that blocks are found. 

What am I doing wrong?

**Comment by bananenwilly** [comment]
@backpacker69 helped me to disable minting, which according to him will fix this problem. I'll monitor the host systems performance for the next day or so.

**Comment by peerchemist** [comment]
So is it a bug or not?

**Comment by bananenwilly** [comment]
I reduced number of outputs in that wallet significantly, so it's not exactly reproducible anymore.
Wouldn't mind closing this for now.
