### ISSUE TITLE
MAX_OP_RETURN_RELAY is 83 bytes

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin#501]
Per [RFC-0009](https://github.com/peercoin/rfcs/blob/master/text/0008-increase-op-return-size-limit/0008-increase-op-return-size-limit.md) Peercoin max op_return size is 256 bytes, however reference node is only relaying up to 80 bytes.

https://github.com/peercoin/peercoin/blob/84979d7ed6820041f6632ef30fa2c3294fbf4818/src/script/standard.h#L34

**Comment by sandakersmann** [comment]
I think we should fix this and https://github.com/peercoin/peercoin/issues/500 in a soon to be v0.8.5 release.

**Comment by peerchemist** [comment]
That's an option as well.

**Comment by peerchemist** [comment]
Fixed with: https://github.com/peercoin/peercoin/commit/acec3523b91bfe58f1a20df4a399191dc1483a22
