### ISSUE TITLE
Do not try minting by default

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin#502]
I believe minting by default is not user friendly, mostly because user does not expect such a behaviour and thinks of wallet as a storage rather than active participant in the PoS consensus. In the past we had many complaints by users who have minted by accident, then come to complain about their coins being locked and they don't know why.

To work around this I propose we implement two different "accounts" in the wallet. One account would be normal, "spending" account which PoS minter thread will ignore and not try to mint with them. Second would be "savings" account which will try to participate in PoS process.

This way users can optimize his portfolio and split it between the coins they expect to be ready for spending at any moment and coins which they keep for longer periods of time - coins which will not mint.

To make it easy for the CLI users I propose we introduce new RPC call: "getnewmintingaddress" as analogue to "getnewaddress". 

There should also be a call to move coins from regular account to "minting" or "saving" account.

This is also nicer solution for exchanges, as they do not have to worry about "nominting" flag.

**Comment by peerchemist** [comment]
Alternative to this could be setting up "reserved coins", ie. a some minimum coins that should never be staked.

**Comment by sandakersmann** [comment]
User friendly should not go before security of the network in the main full node client. Light clients can serve the user friendly aspect.

**Comment by sunnyqueen** [comment]
what about making minting only possible when you have encrypted your wallet (so you have to unlock it for minting anyway), it is also better for wallet security imo

**Comment by sandakersmann** [comment]
Not a fan of that suggestion either. I think it is enough that you deactivate minting in the RPC.

**Comment by backpacker69** [comment]
i think that such change must go through regular rfc process before becoming a task for development. this is not a trivial user interface matter, but change of default participation in securing of the network.

our current pos difficulty is low enough as it is, this change would reduce it further. 

i am against this change and the way its managed.
