### ISSUE TITLE
CBignum vs arith_uint256

### ISSUE THREAD

**Issue by BlockMechanic** [peercoin/peercoin#507]
Hello, may i ask why you still included bignum.h after moving from the old source instead of using arith_uint256?

**Comment by peerchemist** [comment]
Some functions are still using the bignum, it's planned to eventually port them to new arithmetic.

**Comment by peerchemist** [comment]
@BlockMechanic do you mind contacting me privately on telegram, discord or us via the foundation@peercoin.net email. We are looking for developers to help out with the next few releases.
