### ISSUE TITLE
Staking=0 as alias for nominting

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin#518]
`staking=0` in  .conf file is commonly used by our forks and clones to stop the minter thread.
To prevent confusion and people trying to stop minter thread on peercoin daemon with this command, node should understand staking as alias for "minting".

**Comment by sandakersmann** [comment]
https://github.com/peercoin/peercoin/commit/2d94739f70cf4428bd67426264585671f0c2e270
