### ISSUE TITLE
Menu Changes for v0.10

### ISSUE THREAD

**Issue by Sentinelrv** [peercoin/peercoin#532]
I would like to implement a number of changes in the menu of the client if possible.

**File Menu Changes:**

1. The M in "Sign message" should be capitalized.

2. The M in "Verify message" should be capitalized.

**Window Menu Changes:**

3. Is the "Minimize" option really necessary here? There is already an icon for this at the top right corner of the window.

4. Is there a better name for this dropdown menu than Window? It's a little vague sounding.

5. The A in "Sending addresses" should be capitalized.

6. The A in "Receiving addresses" should be capitalized.

**Help Menu Changes:**

7. Add a link for the main website called "Peercoin.net." It should link to https://www.peercoin.net/

8. Replace the "Chatroom" link with two other links. The first called "Discord Chat" should link here: https://discord.gg/m294ReV
The second called "Telegram Chat" should link here: https://telegram.me/peercoin Telegram is usually more popular, so I figure we should just list both and let the user decide which one to use.

9. I talked about this one with Peerchemist already, but I'd also like to add a link to the foundation page where all our donation options are located. It should be called "Donate" and will link here: https://www.peercoin.net/foundation

10. The O in "Command-line options" needs to be capitalized

11. I'd also like to include one more link called "Team News" which should link to here: https://talk.peercoin.net/c/announcements/50 The purpose of this is so users can more easily follow our team updates and know when to upgrade.

12. The order of the help menu should be as follows...

- Peercoin.net
- Donate
- Team News
- Discord Chat
- Telegram Chat
- Forum
- Command-line Options
- About Peercoin
- About QT

**Comment by Sentinelrv** [comment]
I was alerted that menu icons are going away, so just ignore those parts of my post related to icons.

**Comment by Sentinelrv** [comment]
I was informed that the menu items in v0.10 have already changed from what they were in v0.9, so I installed the client to check. As a result, I've completely redone my instructions in the initial post. Do you guys agree with my additions in the help menu? Also, I pointed out that I think the name of the "Window" dropdown menu should be changed to something less vague sounding. Any ideas?

**Comment by peerchemist** [comment]
Resolved with https://github.com/peercoin/peercoin/pull/549
