### ISSUE TITLE
Pruning residue in src/qt/intro.cpp

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#534]
We have some pruning residue in src/qt/intro.cpp

![Screenshot from 2020-08-18 18-17-49](https://user-images.githubusercontent.com/6118832/90563076-8c6b9100-e1a3-11ea-9d69-f26b80f89046.png)

![Screenshot from 2020-08-18 18-18-08](https://user-images.githubusercontent.com/6118832/90563117-9beada00-e1a3-11ea-9936-764e663099f1.png)

**Comment by sandakersmann** [comment]
@backpacker69 

We still have the checkbox in the UI after your latest patch:

![Screenshot from 2020-08-27 16-15-30](https://user-images.githubusercontent.com/6118832/91454225-02958500-e881-11ea-8416-b60ac7de4e3b.png)

![Screenshot from 2020-08-27 16-16-02](https://user-images.githubusercontent.com/6118832/91454241-06290c00-e881-11ea-96c1-8ac772ab8e3e.png)

**Comment by backpacker69** [comment]
what about now

**Comment by sandakersmann** [comment]
Looks good now :)
