### ISSUE TITLE
v0.10 does not create P2PKH addres when "getnewaddress" is called

### ISSUE THREAD

**Issue by peerchemist** [peercoin/peercoin#540]
It seems to be enforcing segwit address creation. Notably segwit embeded in P2SH and native bech32 segwit if designated.

> embedded": {
    "isscript": false,
    "iswitness": true,
    "witness_version": 0,
    "witness_program": "59d6829d9c60cb5742d3381db56b02a3378a87cd",
    "pubkey": "02b2281ae266e57875b0600babfe1edfbf9659da6456b7679439f13efa8eeb83c1",

Peercoin has no use of enforcing segwit, it's an optional feature.
Reference node should be defaulting to P2PKH address creation.

**Comment by sandakersmann** [comment]
Yes. _getnewaddress lagacy_ does not work.

**Comment by peerchemist** [comment]
Seems to be resolved with https://github.com/peercoin/peercoin/commit/eeb85c48f9134844a4d5d60fcf37ddb88c336db8
