### ISSUE TITLE
Default data directory on Linux does not match FreeDesktop standards.

### ISSUE THREAD

**Issue by qrpnxz** [peercoin/peercoin#544]
Today in Linux it is customary to put configuration files in `$XDG_CONFIG_HOME/program` or, if `XDG_CONFIG_HOME` is not set or empty, in `$HOME/.config/program`. Peercoin at the moment looks in `$HOME/.program`. Doing this doesn't break anything, it is just rather inconvenient.

[Directory spec reference.](https://specifications.freedesktop.org/basedir-spec/latest/ar01s03.html)

**Comment by qrpnxz** [comment]
Actually, it seems to be doing the right thing. `$HOME/.peercoin` was simply generated because that's the default data directory. However, the default data directory under XDG should be `$XDG_DATA_HOME/peercoin` or, if not set or empty, then `$HOME/.local/share/peercoin`. So that should be considered.

**Comment by peerchemist** [comment]
It's probably too hard to change this at this point, as how it is so far is pretty much accepted standard.
