### ISSUE TITLE
Feature: Add installation packages for Linux (AppImage, Flatpack, native packages etc.)

### ISSUE THREAD

**Issue by dragetd** [peercoin/peercoin#556]
As @peerchemist suggested, it would be nice to have an easy-to-install option for Linux users.

Currently there are Linux builds which can be simply deployed as a tar.gz and extracted. And if you ask me, this is already valid method. We might tweak the presentation/documentation a little, but it works well enough.

There are several alternatives to this. The three common 'universal' package formats are:
- SNAP
Developed by Ubuntu. By default, SNAPs are also only installable via the Ubuntu-store which is a kind-of nasty vendor-lock-in in the FOSS world. https://ubuntu.com/tutorials/create-your-first-snap#1-overview
- AppImage: Simpler packages that can be run also without root permissions. Tho as far as I know there is no real update mechanism next to simply getting a newer AppImage. At least this is something one should consider/check since security-updates can be kind of critical for Peercoin. https://docs.appimage.org/packaging-guide/introduction.html
- Flatpack Similar to SNAP they isolate using namespaces. https://docs.flatpak.org/en/latest/first-build.html

Then there are of course the native package formats for the different distributions. Which integrate perfectly with each Distro and get all the free security updates, mirror hosting and downstream bug-tracker issues. But they are also the most work.

Personally, I think everything that can be built mostly automatically, we should try and leave the user a choice. And maybe we find maintainers for different distributions?

I would like to use this issue to discuss those things separate from the CI/CD discussion in #553 and decide for each alternative if we want it or not. And maybe find some others willing to maintain distro packages. :)

Once we have decided and implemented one or two, we can close this issue and raise only new one if there is a specific request from someone.

**Comment by peerchemist** [comment]
https://github.com/peercoin/packaging

**Comment by peerchemist** [comment]
There is also a deb repo: https://github.com/peercoin/deb-repo

**Comment by dragetd** [comment]
Ahh, I overlooked that one! Thanks for pointing it out. Nice to know!
