### ISSUE TITLE
Minting tab hidden in v0.10

### ISSUE THREAD

**Issue by qrpnxz** [peercoin/peercoin#561]
When you run v0.10 the minting tab is missing on Linux. You can get it to appear again by resizing the window, but there's no indication of this. We should change the default window size so that it shows up.

It's not possible to shrink the window to hide any of the other tabs, so it should also be impossible to hide the minting tab this way.

**Comment by neoncoin-project** [comment]
This can be caused by the sizeHint, generaly due the theme located in src/qt/res/themes/default.qss this is not a issue, but sometimes in some distros with some versions of QT this can happen.

Try change the sizeHint of src/qt/forms/sendcoinsdialog.ui (L#574 & L#575) to:
`      <width>800</width>` 
       `<height>1</height>`

**Comment by Goliath** [comment]
This is still occuring. I won't tell you how much time it took me to find out that I need to resize the window in order to see the button :)
