### ISSUE TITLE
 direct hyperlink for my address

### ISSUE THREAD

**Issue by gvian** [peercoin/peercoin#568]
for example, [my bitcoin address](https://btc.com/3K7Ba2DFyyuGTukNqXEmogG4VgYp2RWnZV)

for my peercoin address `PENnyj6dvEqaAKtqh9tV9KzRKc4N5EWfeH`, how?

**Comment by ihavenoface** [comment]
Try https://chainz.cryptoid.info/ppc/address.dws?PENnyj6dvEqaAKtqh9tV9KzRKc4N5EWfeH.htm
