### ISSUE TITLE
Unit tests?

### ISSUE THREAD

**Issue by MatthewLM** [peercoin/peercoin#57]
There are no unit tests for peercoin, or rather it takes the tests form Bitcoin without adjusting them at all. Wouldn't it be a good idea to create unit tests for peercoin?

**Comment by hrobeers** [comment]
These are fixed by PR https://github.com/ppcoin/ppcoin/pull/112
Should be merged soon.

**Comment by hrobeers** [comment]
This can be closed as PR https://github.com/ppcoin/ppcoin/pull/112 is merged in
