### ISSUE TITLE
When you mint from an address the output ends up in a new legacy address

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#596]
When you mint from a segwit address the output ends up in a new legacy address as you can see here:

https://tblockbook.peercoin.net/block/442971

The output should end up in the same segwit address.

**Comment by sandakersmann** [comment]
The same is happening on mainnet for me now. I mint from a legacy address and it ends up in a new legacy address. When i try to dumpprivkey for that new address I get: "Private key for address PXXXX is not known (code -4)".

I'm able to send my coins back by using coin control features. The new address is not shown, but by choosing the newest transactions under the address I'm minting from (and sending it) I send from the new legacy address.

This should have a high priority to fix, since people can lose their coins. I think it must be related to the HD wallet code. The address I'm minting from was imported with importprivkey.

**Comment by sandakersmann** [comment]
@backpacker69 @peerchemist @ihavenoface You should look at this...

**Comment by backpacker69** [comment]
thanks for finding this, wish it was reported as a separate bug as it's not connected to segwit.
