### ISSUE TITLE
Guix support

### ISSUE THREAD

**Issue by ihavenoface** [peercoin/peercoin#615]
Just noting some findings for the inclusion of Guix in the future.

Building the most recent bitcoin commit works out of the box, although, when using the supplied docker base image one needs to make sure /etc/nsswitch.conf is available: `echo 'hosts: files dns' > /etc/nsswitch.conf`

As of now peercoin, out of the box, throws
```bash
Updating channel 'guix' from Git repository at 'https://github.com/dongcarl/guix.git'...
Authenticating channel 'guix', commits 9edb3f6 to b3a7c72 (2 new commits)...
guix time-machine: error: commit b3a7c72c8b2425f8ddb0fc6e3b1caeed40f86dee not signed by an authorized key: 09CD D25B 5244 A376 78F6  EEA8 0CC5 2153 1979 91A5
```
This will probably go away once rebased against bitcoin 22, or when backporting `contrib/guix`.

**Comment by ihavenoface** [comment]
Building from scratch is painfully slow. I don't think it's reasonable to include guix with every single commit, unless there is some aggressive caching added.
I estimate some 3 hours on public runners just for a non-cached pipeline.

**Comment by peerchemist** [comment]
Let's worry about that when we get there, focus on what is important for us in the upcoming period.
