### ISSUE TITLE
Coin age incorrectly displayed on new transaction

### ISSUE THREAD

**Issue by ihavenoface** [peercoin/peercoin#616]
On v0.11.1, when receiving any new transaction, the client will display a coin age of 18950+, which does not seem right.

![image](https://user-images.githubusercontent.com/1175752/142764836-94003f9a-0ca6-4e90-b63d-30334a8d6e66.png)

**Comment by peerchemist** [comment]
Yep, it was reported earlier.

Fix is coming sometime next week. Hopefully.

**Comment by ihavenoface** [comment]
Looks good in 354672e6c23b787358897616bdb3db2bf7c8b663.
