### ISSUE TITLE
No option for fully decrypting the wallet

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#635]
Only option now is to decrypt for minting only. An option for fully decrypting the wallet is needed when you for example want to dump private keys in the console.

**Comment by Nagalim** [comment]
Walletpassphrase with a long time parameter can be used for dumping priv keys.

**Comment by Nagalim** [comment]
Use "false" to unlock totally, "true" unlocks for minting only.

**Comment by selfwithin** [comment]
on console use the follwing command. 

"wallate passpharse" , XXX(numbers of seconds you want to unlock wallet for ), false

once you are done. lock the wallet.

and decrupt for minting...

**Comment by sandakersmann** [comment]
Thanks. Worked with false added on the end. I think it should be an option under settings also.

**Comment by belovachap** [comment]
I would also like this feature. I've had to resort to doing the "walletpassphrase with a long timeout" trick for my own use case after not finding this option in the GUI menu.
