### ISSUE TITLE
peercoin-qt on linux hangs often

### ISSUE THREAD

**Issue by belovachap** [peercoin/peercoin#638]
**Expected behavior**

When moving from section to section in the peercoin-qt app it should be responsive.

**Actual behavior**

I get hit with a "Application is not responding" pop-up often.

![image](https://user-images.githubusercontent.com/396781/197767960-6fba319c-0230-4c1e-ae2d-abada54988d4.png)

**To reproduce**

~~Have a wallet that you've been minting with for many years? I think having a ton of transactions _might_ have something to do with the performance issue.~~

Point the datadir to a destination with higher latency than a SSD, such as NFS NAS. Begin minting with a mature wallet. Notice that turning off minting improves the responsiveness of the application significantly.

**System information**

v0.11.8

Ubuntu 20.04 / AMD / SSD + NAS (`-datadir` is pointing to the NAS)

**Comment by peerchemist** [comment]
And without datadir on NAS? What happens with local datadir?

**Comment by belovachap** [comment]
@peerchemist I think this happened before I migrated to using a NAS as well but I'll copy it over to the SSD and see if that helps :+1:

**Comment by selfwithin** [comment]
Rebuilt DataDir from scatch...

**Comment by peerchemist** [comment]
@belovachap I'm a GNOME user as well. Lately, GNOME has been hypersensitive about "not-responding". And I am pretty sure it's about slow I/O.

**Comment by sandakersmann** [comment]
I have the same issue after updating to Ubuntu 20.04

**Comment by belovachap** [comment]
Alright, I copied the datadir over to my local ssd and that completely removed the not responding pop-up. I just went back to using the NAS and the not responding pop-up returns.

**Comment by selfwithin** [comment]
you are right having a ton of transactions might have something to do with the performance issue.

**Comment by belovachap** [comment]
I wonder if other clients, like Bitcoin, also suffer when using the NAS as their datadir :thinking:

**Comment by belovachap** [comment]
I've been messing around with different combinations of software and scenarios and here's what I've learned. Bitcoin v22 and v23 doesn't have any issues even when running on the NAS. Peercoin is responsive while minting and not minting with a SSD datadir. Peercoin is responsive while not minting and running on the NAS. Peercoin is unresponsive while minting and running on the NAS.

This seems to suggest that minting while being backed by a slower disk device is causing the GUI to become unresponsive.

**Comment by peerchemist** [comment]
Try v0.12 branch as well.
