### ISSUE TITLE
github actions are failing to build release-0.12

### ISSUE THREAD

**Issue by backpacker69** [peercoin/peercoin#641]
there's some issue with build process, currently it fails on macosx build with missing sdk files. possibly other issues exist also.

**Comment by peerchemist** [comment]
@ihavenoface care to take a look? Branch `release-0.12`.

Also, do you think we should port the build system to guix?

**Comment by ihavenoface** [comment]
Incidentally I started working on this some 3 hours ago.

**Comment by ihavenoface** [comment]
As for guix, I don't think I can deal with it in a timely fashion and also make it look good.

**Comment by peerchemist** [comment]
Guix stuff can wait for post final release-0.12 and the hard fork.

**Comment by backpacker69** [comment]
i've fixed the two issues you've outlined, but we have different issue further on, can you please have a look

**Comment by ihavenoface** [comment]
Sidenote: While the builds are passing now, I have not yet checked if the release portion still works as expected. Shouldn‘t be much of an issue however.

**Comment by backpacker69** [comment]
well done mate, seems to be done!
