### ISSUE TITLE
`release-12` Transactions tab icon doesn't match other tabs

### ISSUE THREAD

**Issue by belovachap** [peercoin/peercoin#646]
![image](https://user-images.githubusercontent.com/396781/200220230-7762b7f6-8c29-4dd0-9615-84b24753b6a6.png)

All of the other tabs have white outlined icons, Transactions now has something different looking.

#### Useful skills:

Qt5 GUI

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by backpacker69** [comment]
fixed
