### ISSUE TITLE
`release-12` Still using v0.11 splash screen on startup

### ISSUE THREAD

**Issue by belovachap** [peercoin/peercoin#647]
![image](https://user-images.githubusercontent.com/396781/200222426-ad567703-4ee6-41e6-9303-43f7b2a1e325.png)

I've heard we want a lady bug for v0.12 :lady_beetle: 

#### Useful skills:

Inkscape and Qt5 GUI

#### Want to work on this issue?

The purpose of the `good first issue` label is to highlight which issues are suitable for a new contributor without a deep understanding of the codebase.

You do not need to request permission to start working on this. You are encouraged to comment on the issue if you are planning to work on it. This will help other contributors monitor which issues are actively being addressed and is also an effective way to request assistance if and when you need it.

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by backpacker69** [comment]
thank you it's fixed now

**Comment by belovachap** [comment]
awesome sauce, i bet it will look super cool now :rocket:
