### ISSUE TITLE
`release-12` `walletpassphrase` command in console returns an error

### ISSUE THREAD

**Issue by belovachap** [peercoin/peercoin#648]
**Expected behavior**

I go to the console in the Qt application and unlock my wallet using the `walletpassphrase` command.

**Actual behavior**

I go to the console in the Qt application and unlock my wallet using the `walletpassphrase` command and receive an error! It looks like my wallet is now unlocked for what it's worth but there wasn't an error in v0.11.

![image](https://user-images.githubusercontent.com/396781/200222900-b3ccf334-c72a-424d-8cd3-2ba518fffd28.png)

**To reproduce**

See `Actual behavior` above.

**System information**

`release-0.12` bbab6480039c34c5c92c4979249987de792fd48d, Ubuntu 22.04

**Comment by backpacker69** [comment]
fixed
