### ISSUE TITLE
`release-0.12` - Pruning residue in welcome screen

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#665]
![Screenshot from 2022-12-11 01-43-10](https://user-images.githubusercontent.com/6118832/206881164-edfa761f-15cf-4ded-800d-2e92b6da8ad5.png)

**Comment by lateminer** [comment]
There are some more places with pruning leftovers in Qt code. I'll come with a PR soon.

**Comment by lateminer** [comment]
It is solved in #668.

**Comment by sandakersmann** [comment]
Fixed in: https://github.com/peercoin/peercoin/commit/56c9a7fdd4d0afc816c21fa19edc50eb997e0942
