### ISSUE TITLE
`release-0.12` - Not able to create new wallet

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#666]
Not able to create new wallet when starting from scratch. If you type "createwallet testnet" into the console you get this error: "Compiled without sqlite support (required for descriptor wallets) (code -4)"

![Screenshot from 2022-12-11 02-34-09](https://user-images.githubusercontent.com/6118832/206882467-74ba6a52-90fd-4d98-ac1b-dbe917d5f6a5.png)

**Comment by sandakersmann** [comment]
Yes. Built on Ubuntu 22.04

```
git clone -b release-0.11 https://github.com/peercoin/peercoin
cd peercoin
./autogen.sh
./configure --with-gui=qt5 --with-incompatible-bdb
make
```

**Comment by ihavenoface** [comment]
You're missing sqlite, which is mentioned here https://github.com/peercoin/peercoin/blob/release-0.12/doc/build-unix.md#linux-distribution-specific-instructions
`sudo apt install libsqlite3-dev`
