### ISSUE TITLE
v0.12.0 Error on submitblock

### ISSUE THREAD

**Issue by laakie** [peercoin/peercoin#682]
Submitblock fails with error:
`{"code":-32603,"message":"Wallet context not found"}` 
All worked without any problems on v0.11.8
I can load the wallet, spend coins, sign messages without problems on the new v0.12.0 wallet.
Wallet build from source on ubuntu 20.04 LTS x86_64-pc-linux-gnu

The new wallet that fails to submit:
{
  "walletname": "wallet.dat",
  "walletversion": 169900,
  "format": "bdb",
  "txcount": 13507,
  "keypoololdest": 1675768456,
  "keypoolsize": 999,
  "hdseedid": "xxxxxx",
  "keypoolsize_hd_internal": 1000,
  "private_keys_enabled": true,
  "avoid_reuse": false,
  "scanning": false,
  "descriptors": false,
  "external_signer": false
}

The old working wallet:
{
  "walletname": "wallet.dat",
  "walletversion": 159900,
  "txcount": 24550,
  "keypoololdest": 1663968051,
  "keypoolsize": 1001,
  "hdseedid": "xxxxx",
  "keypoolsize_hd_internal": 993,
  "unlocked_until": 0,
  "unlocked_minting_only": false,
  "private_keys_enabled": true,
  "avoid_reuse": false,
  "scanning": false
}

**Comment by peerchemist** [comment]
Thanks for report.

**Comment by backpacker69** [comment]
please try the latest commit in release-0.12 branch

**Comment by laakie** [comment]
Confirmed working with the changes made.
Thanks for the quick fix so that consensus can be reached for v12 update.
Do I understand correctly that signing the block isn't required anymore?

**Comment by backpacker69** [comment]
thank you for trying the update early and reporting the issue, it would have been a lot more stress in April. 

since peercoin v0.8 we no longer require signatures on POW blocks and since POS blocks are produced inside the wallet itself via different path, there really is no need for signing code in this rpc method.
