### ISSUE TITLE
release-0.12: (testnet) exception on wallet close

### ISSUE THREAD

**Issue by lateminer** [peercoin/peercoin#684]
When closing an empty wallet on Peercoin testnet, an exception is thrown:

```
************************
EXCEPTION: St13runtime_error       
Error: Keypool ran out, please call keypoolrefill first.       
peercoin in ThreadStakeMinter()       

terminate called without an active exception
Aborted (core dumped)
```

**Comment by backpacker69** [comment]
can't replicate the bug. started with no wallet, created empty non descriptor wallet. closed it. no crash

**Comment by lateminer** [comment]
There is no error when you create a wallet, on the first run. Try to close Peercoin, run it and close once again.
(By the way, descriptor wallets should rather be disabled by default).

**Comment by lateminer** [comment]
Valgrind output:
`Valgrind output:
`==10397== Memcheck, a memory error detector
==10397== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==10397== Using Valgrind-3.18.1 and LibVEX; rerun with -h for copyright info
==10397== Command: ./peercoin-qt -testnet
==10397== 
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x10B1AFA7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x10E9FE87: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x10F1FEB7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0xFC885A7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0xFD07A27: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0xFD891D7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0xFDF49A7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x12264267: ???
==10397== 
==10397== Thread 10 b-minter:
==10397== Invalid read of size 8
==10397==    at 0x532E5D: std::_Function_handler<void (), node::MintStake(std::shared_ptr<wallet::CWallet>, node::NodeContext&)::{lambda()#1}::operator()() const::{lambda()#1}>::_M_invoke(std::_Any_data const&) (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x77B8CE: util::TraceThread(char const*, std::function<void ()>) (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x52A5F5: std::thread::_State_impl<std::thread::_Invoker<std::tuple<node::MintStake(std::shared_ptr<wallet::CWallet>, node::NodeContext&)::{lambda()#1}> > >::_M_run() (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x1918F63: execute_native_thread_routine (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x4C18B42: start_thread (pthread_create.c:442)
==10397==    by 0x4CA9BB3: clone (clone.S:100)
==10397==  Address 0x12dfd350 is on thread 20's stack
==10397==  10224 bytes below stack pointer
==10397== 
==10397== Invalid read of size 8
==10397==    at 0x532E60: std::_Function_handler<void (), node::MintStake(std::shared_ptr<wallet::CWallet>, node::NodeContext&)::{lambda()#1}::operator()() const::{lambda()#1}>::_M_invoke(std::_Any_data const&) (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x77B8CE: util::TraceThread(char const*, std::function<void ()>) (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x52A5F5: std::thread::_State_impl<std::thread::_Invoker<std::tuple<node::MintStake(std::shared_ptr<wallet::CWallet>, node::NodeContext&)::{lambda()#1}> > >::_M_run() (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x1918F63: execute_native_thread_routine (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x4C18B42: start_thread (pthread_create.c:442)
==10397==    by 0x4CA9BB3: clone (clone.S:100)
==10397==  Address 0x12dfd358 is on thread 20's stack
==10397==  10216 bytes below stack pointer
==10397== 
==10397== Thread 1:
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x1E807067: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x2123E737: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x1ECFDAA7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x29D2CEC7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x365C4A77: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x366B7C07: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x2B3691A7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x4ED4577: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x110DF7E7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x1250B2A7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x21D0D0E7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x6C1D167: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x71BC827: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x12380DD7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x34F54427: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x72A2E07: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x113ABCC7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x35940D77: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x1E706027: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x6D7C6C7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x7347EE7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x10B98167: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0xFDEE547: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x2B9E3A27: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x2B362567: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x34543DE7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x34A16A47: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x1F1E4587: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x25375B47: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x2A531607: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x2AF825E7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x31E51CE7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x1F864167: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x1F6CC9B7: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x27621B17: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x25057167: ???
==10397== 
==10397== Conditional jump or move depends on uninitialised value(s)
==10397==    at 0x10DE7C39: ???
==10397==    by 0x352FF427: ???
==10397== 
terminate called without an active exception
==10397== 
==10397== Process terminating with default action of signal 6 (SIGABRT)
==10397==    at 0x4C1AA7C: __pthread_kill_implementation (pthread_kill.c:44)
==10397==    by 0x4C1AA7C: __pthread_kill_internal (pthread_kill.c:78)
==10397==    by 0x4C1AA7C: pthread_kill@@GLIBC_2.34 (pthread_kill.c:89)
==10397==    by 0x4BC6475: raise (raise.c:26)
==10397==    by 0x4BAC7F2: abort (abort.c:79)
==10397==    by 0x30C311: __gnu_cxx::__verbose_terminate_handler() [clone .cold] (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x1895D8B: __cxxabiv1::__terminate(void (*)()) (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x1895DF6: std::terminate() (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x4A6697: std::thread::~thread() (in /home/***/dev/peercoin/src/qt/peercoin-qt)
==10397==    by 0x4BC9494: __run_exit_handlers (exit.c:113)
==10397==    by 0x4BC960F: exit (exit.c:143)
==10397==    by 0x4BADD96: (below main) (libc_start_call_main.h:74)
==10397== 
==10397== HEAP SUMMARY:
==10397==     in use at exit: 401,154 bytes in 7,932 blocks
==10397==   total heap usage: 6,180,286 allocs, 6,172,354 frees, 761,967,057 bytes allocated
==10397== 
==10397== LEAK SUMMARY:
==10397==    definitely lost: 1,976 bytes in 24 blocks
==10397==    indirectly lost: 4,281 bytes in 13 blocks
==10397==      possibly lost: 6,496 bytes in 8 blocks
==10397==    still reachable: 388,401 bytes in 7,887 blocks
==10397==         suppressed: 0 bytes in 0 blocks
==10397== Rerun with --leak-check=full to see details of leaked memory
==10397== 
==10397== Use --track-origins=yes to see where uninitialised values come from
==10397== For lists of detected and suppressed errors, rerun with: -s
==10397== ERROR SUMMARY: 47 errors from 47 contexts (suppressed: 0 from 0)
Aborted (core dumped)``
