### ISSUE TITLE
`release-0.12` - Wrong copyright year on splash screen

### ISSUE THREAD

**Issue by sandakersmann** [peercoin/peercoin#695]
Bitcoin started in 2009

![PeercoinSplash](https://user-images.githubusercontent.com/6118832/230438472-5ed28c34-8226-4329-b5c8-21140f5fb5c8.png)

**Comment by peerchemist** [comment]
Perhaps Bitcoin should be deleted.

**Comment by sandakersmann** [comment]
I think that would violate copyright.

**Comment by sandakersmann** [comment]
Peercoin started in 2011

![Screenshot from 2023-04-06 18-21-26](https://user-images.githubusercontent.com/6118832/230438926-cd7937e7-5613-4d35-834b-de2a821a5d63.png)

**Comment by peerchemist** [comment]
> I think that would violate copyright.

What copyright? Code is MIT licensed.

**Comment by sandakersmann** [comment]
Which mean you must reference where it came from.

**Comment by peerchemist** [comment]
That's BSD-3 license you are thinking, the MIT license carries no obligations.

**Comment by sandakersmann** [comment]
No: https://github.com/peercoin/peercoin/blob/master/COPYING#L13-L14

**Comment by lateminer** [comment]
Should be solved by https://github.com/peercoin/peercoin/pull/720.
