### ISSUE TITLE
Please check minimum required version of glibc

### ISSUE THREAD

**Issue by evermorn** [peercoin/peercoin#696]
According to dependencies, minimum required version of glibc is 2.18

**Expected behavior**

Succesfully build peercoin on ubuntu 16.04( glibc == 2.23 ) and all is working fine.

**Actual behavior**

Actually on build stage there are no errors, but when I try to run binary peercoind I see segfault:
`segfault at 20000562170 ip 0000562146393c15 sp 00007fff662a3970 error 4 in peercoind[5621462e3000+1023000]`
Debug with strace and gdb give me this:

> 
(gdb) bt
0x0000555555604c15 in ?? ()
0x0000555555604c2a in ?? ()
0x0000555555604c2a in ?? ()
0x0000555555d5d22f in ?? ()
0x0000555555d5d376 in ?? ()
0x00005555555dfa66 in ?? ()
0x00007ffff6d03840 in __libc_start_main (main=0x5555555df4ee, argc=5, argv=0x7fffffffe568, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffe558) at ../csu/libc-start.c:291
0x00005555555df0f9 in ?? ()

For example, there is no such segfault in build with ubuntu 20.04( glibc == 2.31 )

**To reproduce**

Build peercoin v0.12.2 on ubuntu 16.04 using build instruction, including depends, in this repo.

**System information**

**Comment by backpacker69** [comment]
actually, lowest glibc that works is 2.29, see commit 05049c48ca648ca7fbfced3faf672a53f4e525f6
