### ISSUE TITLE
Crash on Open

### ISSUE THREAD

**Issue by hiroo717** [peercoin/peercoin#700]
Have tried to upgrade to v12. On Windows 10. Using the `-datadir=` flag. Have tried deleting all files other than `wallet.dat` in the data directory. Peercoin gui is visible (blank) for a moment and then disappears - I assume it has crashed. I don't know how to troubleshoot, debug or the location of the log files. Have tried messaging on discord. If anyone can help, would appreciate :-)

**Comment by MatthewLM** [comment]
Hi, are you able to provide the recent contents of the debug.log file in your datadir that may show an error? You can also run the client with `-debug` which may provide more useful information to the log file.

**Comment by hiroo717** [comment]
Thanks. I did a search for *error* in the `debug.log` file but nothing interesting other than some error about the location of `db.log`:

`<TIMESTAMP> BerkeleyEnvironment::Open: LogDir=<PATH TO PEERCOIN DATADIR>\database ErrorFile=<PATH TO PEERCOIN DATADIR>\db.log`

I tried launching without the `-datadir=` flag and the GUI did show and asked me the location of my datadir. I pointed it to the same location but then it crashed. The datadir is on a different drive in my case, if that makes any difference?  

Not sure where Peercoin is saving the datadir location as now I can't reset it to the default location.  

Still don't know what the issue is here. Would appreciate any more help/guidance.

**Comment by backpacker69** [comment]
@hiroo717 can you please zip debug log and send it to backpacker69@protonmail.com for analysis, it could be something to do with permissions on datadir, but it would be quickest to see for myself

**Comment by hiroo717** [comment]
@backpacker69  Ok done.

**Comment by hiroo717** [comment]
>this is rather old log file, last entry is on 15th of May and it used to run properly and exit without errors. can you also paste your peercoin.conf as well?

Thanks for your help. That is the only `debug.log` file I have and the age is probably consistent with my inability to launch the application for some time. I do not have any `peercoin.conf` that I can locate, at least not in the root of the data dir.

**Comment by backpacker69** [comment]
you've had peercoin v0.12.3 working properly on your machine in May, can you try to revert to it and see if it fixes the problem? https://github.com/peercoin/peercoin/releases/tag/v0.12.3ppc

**Comment by hiroo717** [comment]
I have just tried the version you have recommended and the same issue occurs whether or not I use the `datadir` flag. The GUI shows briefly with a white background and then crashes/disappears. When using the `datadir` flag a file called `settings.json` gets created which contains the following text: `{ }`. No `debug.log` file is created.

**Comment by MatthewLM** [comment]
You could try running it from a command line with `-printtoconsole` and `-debug` to see if anything is printed to the console.

**Comment by hiroo717** [comment]
@MatthewLM Thanks for the suggestion. I have tried this and nothing gets printed to the console. Again, the GUI flashes up in white for a moment and then disappears. A `settings.json` file gets created which contains the following text: `{ }`. No `debug.log` file is created.

**Comment by backpacker69** [comment]
does v11 work and produce debug.log?

**Comment by hiroo717** [comment]
I have just tried v0.11.8 and it is working fine. A `debug.log` file is also created.

**Comment by hiroo717** [comment]
Closing as for some reason everything is working now.    

Only possible differences are running the installer as administrator, installing after rebooting the system, installing only when all other programs are closed or ensuring that the firewall allowed outgoing connections before opening the application.    

Not sure what else helped but the blockchain is now downloading.    

Thanks @backpacker69 and @MatthewLM  for your help.
