### ISSUE TITLE
`release-0.12` - Memory consumption on Raspberry Pi (ARMv7)

### ISSUE THREAD

**Issue by lateminer** [peercoin/peercoin#727]
`release-0.12` has an issue with memory consuption on a Raspberry Pi device (Model 3B with 1GB RAM and 2GB swap). After running for some time it consumes all memory and Pi becomes inaccessible.
`release-0.11` works flawlessly.

**Comment by peerchemist** [comment]
Hello,

I have noticed the same in my tests. However, we were not able to find a memleak. It seems that recent bitcoin-core iterations are just more memory hungry, and we have picked up their changes. Please try out v0.13 build, perhaps there is a difference.

**Comment by lateminer** [comment]
I have a feeling it will be the same as I have noticed similar behaviour in Blackcoin after performing an upgrade to Bitcoin Core 25.x. I also didn't find any memory leaks.
But I will try 0.13 anyway.

**Comment by lateminer** [comment]
Looks the same for 0.13.
