### ISSUE TITLE
`release-0.13` - generatetoaddress doesn't work

### ISSUE THREAD

**Issue by lateminer** [peercoin/peercoin#732]
`generatetoaddress` RPC on `release-0.13` doesn't create new blocks on regtest and returns an empty array as a result.

**Comment by backpacker69** [comment]
it does work, you just have to specify a larger maxtries parameter

**Comment by lateminer** [comment]
Not working on my side.

```
20:37:44 generatetoaddress 1 mzjFp8PkJHACcCozEz6axsjEvRuoyFXp5i 999999999
20:48:32 [ ]
```

```
20:48:56 generatetoaddress 1 mzjFp8PkJHACcCozEz6axsjEvRuoyFXp5i 2147483647
21:12:06 [ ]
```

**Comment by backpacker69** [comment]
please try commit 0752ef0315361210e75c58ed57aa7274f9e5f7d6

**Comment by lateminer** [comment]
The result is being returned much faster, but the coins aren't generated.

**Comment by backpacker69** [comment]
what about this one: e5bb73b9150bbce0e3665337c213fecf4a881a66

**Comment by lateminer** [comment]
This one helps.
