### ISSUE TITLE
`v0.14.9` regression: unencrypted wallet prompts for password

### ISSUE THREAD

**Issue by ihavenoface** [peercoin/peercoin#781]

**Comment by backpacker69** [comment]
> _No description provided._

what was the earliest version that didn't exhibit such behaviour?

**Comment by ihavenoface** [comment]
v0.14.8

**Comment by backpacker69** [comment]
can you please test release-0.14 3f324211ab

**Comment by ihavenoface** [comment]
Works fine on https://github.com/peercoin/peercoin/commit/3f324211ab0532757285bc7316afb2dc1bbb872d

**Comment by backpacker69** [comment]
thank you for reporting
