### ISSUE TITLE
Peercoin PoW / Miningcore

### ISSUE THREAD

**Issue by goodthebest** [peercoin/peercoin#788]
I setup a peercoin mining pool blocks are being submitting by the pool however they are not being accepted.
Since peercoin now has POW and POS. Do we need to add any particular flag in peercoin.conf file? Will it mining as usual or there needs to be made any changes in the stratum to adjust it? Please advise. I'm using Miningcore software.

**Comment by peerchemist** [comment]
> I setup a peercoin mining pool blocks are being submitting by the pool however they are not being accepted.

Can you post a debug.log from the node? If the blocks are getting rejected indeed, there should be something about that in the debug.log.

> Since peercoin now has POW and POS.

Peercoin has always had both PoS and PoW blocks. :)

> Do we need to add any particular flag in peercoin.conf file?

Probably not.

BTW, it seems the miningcore software you are trying to use has been abandoned by the author in October '23.

**Comment by belovachap** [comment]
Hello! It might not be exactly tailored to your situation (it's meant more for solo mining and uses a somewhat untested pool mining software) but I wrote an little article on how I setup mining on the testnet (which should be the same process for doing it on the main net).

https://talk.peercoin.net/t/guide-how-to-solo-mine-peercoin/16353

I currently run a small platoon of USB gekko science miners on the Peercoin mainnet using the blog ideas. I'm still waiting for the lucky day when I actually produce a block :)
