### ISSUE TITLE
Can't send funds

### ISSUE THREAD

**Issue by ClaudiuPID** [peercoin/peercoin#86]
Using the development version of ppcoind.
/root/ppcoin/src/ppcoind --help | grep vers
PPCoin version v0.4.0ppc-1915-g4536df1-beta

/root/ppcoin/src/ppcoind listaccounts
{
    "" : 325.17000000
}

/root/ppcoin/src/ppcoind sendfrom "" PSomeaddress 100
error: {"code":-4,"message":"Insufficient funds"}

I tried sending using different options but none works.

Any ideas how to get this working?

**Comment by Thireus** [comment]
Don't forget to subtract the transaction fees (0.01 PPC) :)

**Comment by ClaudiuPID** [comment]
I was trying to send 100 ppc and my balance shows 325.17
And something strange is the listunspent function which returns an empty string.

**Comment by FuzzyBearBTC** [comment]
It looks to me like you are trying to send from an account not an address, you can have many addresses linked to an account and you should be specifying the address that you want to send from I believe
