### ISSUE TITLE
listunspent

### ISSUE THREAD

**Issue by ethought** [peercoin/peercoin#95]
Why is listunspent not supported in ppcoin??

This is causing us real problems.

**Comment by mably** [comment]
Could you tell us a bit more about your listunspent need?

**Comment by ethought** [comment]
I run a service where users tend to make many small deposits. After thousands of small incoming transactions the wallet is unable to send transactions as I get "Transaction Too Large" errors. All other currencies I support have listunspent capability so I can clean dust using listunspent and then create raw transactions to combine dust with one large transaction. Without listunspent my script will not work and users withdrawals are failing.

**Comment by sigmike** [comment]
Peerunity supports `listunspent`: https://github.com/Peerunity/Peerunity/blob/master/src/bitcoinrpc.cpp#L2776
